output_dir: './outputs'

data:
  data_path: './buffers/data/sdvae_f8c4/train_256'
  fid_reference_file: './buffers/refs/in1k256_fid_ref.npz'
  image_size: 256
  num_classes: 1000
  num_workers: 8
  latent_norm: False
  latent_multiplier: 0.18215

vae:
  type: 'sdvae_ema_f8c4'
  downsample_ratio: 8

model:
  type: DDT-XL/2
  in_chans: 4

train:
  global_seed: 1

transport:
  type: ReLinear

sample:
  ckpt: "0000000.pt"
  type: UNI
  cfg_scale: 2.0
  cfg_interval: [0.30, 1.00]
  sampling_steps: 50
  stochast_ratio: 0.0
  extrapol_ratio: 0.28
  sampling_order: 1
  time_dist_ctrl: [1.17, 0.8, 1.1]
  rfba_gap_steps: [0.001, 0.001]
  per_batch_size: 125
  fid_sample_num: 50000
