output_dir: './outputs'

data:
  data_path: './buffers/data/vavae_f16d32/train_256'
  fid_reference_file: './buffers/refs/in1k256_fid_ref.npz'
  image_size: 256
  num_classes: 1000
  num_workers: 8
  latent_norm: True
  latent_multiplier: 1.0

vae:
  type: 'vavae_f16d32'
  downsample_ratio: 16

model:
  type: LightningDiT-XL/1
  in_chans: 32

train:
  global_seed: 0

transport:
  type: ReLinear

sample:
  ckpt: "0000000.pt"
  type: UNI
  cfg_scale: 6.7
  cfg_interval: [0.125, 1.0]
  sampling_steps: 50
  stochast_ratio: 0.0
  extrapol_ratio: 0.5
  sampling_order: 1
  time_dist_ctrl: [1.17, 0.8, 1.1]
  rfba_gap_steps: [0.001, 0.001]
  per_batch_size: 125
  fid_sample_num: 50000
